### ISSUE TITLE
infra: Add test coverage

### ISSUE THREAD

**Issue by AbdelStark** [keep-starknet-strange/ziggy-starkdust#13]
### Description

Investigate using [kcov](https://github.com/SimonKagstrom/kcov) or the suggestions from this [code coverage for zig article](https://zig.news/squeek502/code-coverage-for-zig-1dk1) to add test coverage to the project.

### Acceptance Criteria

- Integrate a code coverage tool
- Ensure that the coverage reports are accessible and easy to read
- Add coverage checks to the CI/CD pipeline

**Comment by julienbrs** [comment]
Hi @abdelhamidbakhta, can I please take this issue?

**Comment by tcoratger** [comment]
> Hi @abdelhamidbakhta, can I please take this issue?

Hey @julienbrs it's a continuous process on the repo:
- We try to add unit tests as we develop so as not to have gaps and debts on this.
- Of course we are not perfect so there must certainly be some missing (we find new missing ones every week).

I am therefore going to close this issue which has now become too generic but do not hesitate to reach out on our Telegram group, we will either find a missing test issue or another issue for you :)
