### ISSUE TITLE
feat: improve test coverage of `CairoVM` core functions

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#131]
### In `updatePc`, in the switch, expressions like this one:
https://github.com/keep-starknet-strange/cairo-zig/blob/de93e4e4b968214a9363b3aa8f171ecb3ce19fc5/src/vm/core.zig#L435
are too verbose and can be replaced by:
```
.Regular => { // Update the PC.
```

### In `updateAp`, one configuration is not tested properly at the moment:
- If `instruction.ap_update` is `.Add`, the configuration resulting in `try self.run_context.ap.*.addMaybeRelocatableInplace(val);` is not tested at the moment (only `error.ApUpdateAddResUnconstrained` is).

## The following methods have no unit tests and all configurations must be tested here:
- `addOperands`:
https://github.com/keep-starknet-strange/cairo-zig/blob/de93e4e4b968214a9363b3aa8f171ecb3ce19fc5/src/vm/core.zig#L659-L686
- `mulOperands`:
https://github.com/keep-starknet-strange/cairo-zig/blob/de93e4e4b968214a9363b3aa8f171ecb3ce19fc5/src/vm/core.zig#L694-L707
- `subOperands`:
https://github.com/keep-starknet-strange/cairo-zig/blob/de93e4e4b968214a9363b3aa8f171ecb3ce19fc5/src/vm/core.zig#L713-L728

**Comment by javimaravillas** [comment]
Please, assign me this issue

**Comment by tcoratger** [comment]
> Please, assign me this issue

@javimaravillas Just assigned
