### ISSUE TITLE
feat: add `getFelt252Range` method in `Memory` structure

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#193]
## Description

The `getFelt252Range` function is an essential method in Rust for retrieving a range of `Felt252` values from a given memory address over a specified size. This method ensures that the values within this range are not missing and are all of type `Felt252`.

## Objective

Request the equivalent implementation of the `getFelt252Range` function from Rust in Zig to ensure consistency in functionalities between languages and facilitate code portability or migration utilizing this feature.

## Example of Zig implementation

```zig
pub fn getFelt252Range(
    self: *Self,
    addr: Relocatable,
    size: usize,
) ![]const Felt252 {
    // Implementation of the function...
}
```

## Reference

Reference for the Rust implementation: https://github.com/lambdaclass/cairo-vm/blob/4089b469ae855414b098abed1fd15f73b03ab7e1/vm/src/vm/vm_memory/memory.rs#L470-L482

**Comment by ptisserand** [comment]
Hi, can I work on this issue ?

**Comment by tcoratger** [comment]
> Hi, can I work on this issue ?

@ptisserand Assigned
