### ISSUE TITLE
feat: enhancement of Bitwise Instance Definition implementation

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#213]
## Description

We aim to enhance our current implementation of the bitwise instance definition within the Cairo Zig codebase. The existing implementation can be found [here](https://github.com/keep-starknet-strange/cairo-zig/blob/main/src/vm/types/bitwise_instance_def.zig).

The goal is to implement a complete and proper version of the bitwise instance definition, adhering to standards and ensuring comprehensive test coverage.

## References

- [Rust Implementation Reference](https://github.com/lambdaclass/cairo-vm/blob/8887e60f7ea5459188cb6624acc908ad29e75f60/vm/src/types/instance_definitions/bitwise_instance_def.rs)
- [Python Implementation Reference](https://github.com/starkware-libs/cairo-lang/blob/51c287ac441ea0295775dce743470f87e395d4b1/src/starkware/cairo/lang/builtins/bitwise/instance_def.py)

**Comment by jobez** [comment]
I had began refactoring it to be in line with the BuiltinRunner conventions #206
