### ISSUE TITLE
feat: Ecdsa Instance Definition Enhancement

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#215]
## Description
The current Ecdsa Instance Definition in our Cairo Zig codebase requires enhancements: [Ecdsa Instance Definition](https://github.com/keep-starknet-strange/cairo-zig/blob/main/src/vm/types/ecdsa_instance_def.zig).

## Objectives
- Implement improvements within the Ecdsa Instance Definition.
- Enhance test coverage for thorough validation and accuracy.

## Reference
- [Rust Implementation Reference](https://github.com/lambdaclass/cairo-vm/blob/8887e60f7ea5459188cb6624acc908ad29e75f60/vm/src/types/instance_definitions/ecdsa_instance_def.rs)

**Comment by ptisserand** [comment]
Can I work on this one ?

**Comment by tcoratger** [comment]
> Can I work on this one ?

Assigned
