### ISSUE TITLE
feat: Range Check Instance Definition Enhancement

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#219]
## Description
The Range Check Instance Definition in our Cairo Zig codebase requires enhancements: [Range Check Instance Definition](https://github.com/keep-starknet-strange/cairo-zig/blob/main/src/vm/types/range_check_instance_def.zig).

## Objectives
- Implement improvements within the Range Check Instance Definition.
- Enhance test coverage for thorough validation and accuracy.

## References
- [Rust Implementation Reference](https://github.com/lambdaclass/cairo-vm/blob/8887e60f7ea5459188cb6624acc908ad29e75f60/vm/src/types/instance_definitions/range_check_instance_def.rs)
- [Python Implementation Reference](https://github.com/starkware-libs/cairo-lang/blob/51c287ac441ea0295775dce743470f87e395d4b1/src/starkware/cairo/lang/builtins/range_check/instance_def.py)

**Comment by oxlime** [comment]
would like to finish this one

**Comment by tcoratger** [comment]
@oxlime Assigned :)
