### ISSUE TITLE
feat: implement the pedersen hash primitive

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/ziggy-starkdust#22]
### Description
Use the [reference](https://docs.starkware.co/starkex/crypto/pedersen-hash-function.html) and implementation examples to implement the missing primitive. 

### Acceptance Criteria
Implement the logic like [here](https://github.com/starkware-libs/crypto-cpp/blob/78e3ed8dc7a0901fe6d62f4e99becc6e7936adfd/src/starkware/crypto/ffi/js/crypto.js#L37) and add tests to ensure it works correctly.

**Comment by bajpai244** [comment]
@lana-shanghai I can take this one :)

**Comment by lana-shanghai** [comment]
Done, sir! :)

**Comment by edisontim** [comment]
I've talked to @bajpai244 about the issue and he said I could take this, can you assign me @lana-shanghai ? :)

**Comment by edisontim** [comment]
Has there been any talk of using the C wrapper of lambda_class for the pedersen_hash primitive but also for other built-in primitives?
