### ISSUE TITLE
tests: add unit tests for `runInstruction` function of `CairoVM` structure

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#225]
## Objective
The `runInstruction` function within the `CairoVM` structure lacks a comprehensive suite of unit tests to ensure its robustness and accuracy.

## Current Status
At present, the [implementation of the runInstruction function](https://github.com/keep-starknet-strange/cairo-zig/blob/2baaeb78eca08ff794eaeeaf9cfc45d9961f50d5/src/vm/core.zig#L276-L310) exists without a comprehensive set of associated tests. This critical function is pivotal to the behavior of the entire VM and involves numerous scenarios that require validation.

## Action Items
- **Test Scenarios Identification:** We aim to create a series of unit tests that cover various scenarios within the `runInstruction` function.
- **Validation of Functionality:** Ensure that the function performs as expected under different conditions, including edge cases and typical usage scenarios.
- **Enhance Code Reliability:** By establishing a robust suite of tests, we ensure the stability and reliability of the Cairo Virtual Machine, validating the behavior of critical functionality.

**Comment by oxlime** [comment]
put me in coach

**Comment by tcoratger** [comment]
> put me in coach

Assigned, we need to find different configurations to test all the features of the function (that is critical) and maybe when you have a doubt, you can compare the instruction set with Rust and try to call the Rust function with this set of instructions in order to compare the results which should be uniform.

**Comment by oxlime** [comment]
Got it, will write equivalent tests in local rust vm for testing.

**Comment by lana-shanghai** [comment]
> Got it, will write equivalent tests in local rust vm for testing.

Hey Lime how is it going? :)

**Comment by oxlime** [comment]
was stuck in the meme trenches, i survived though should have this done soon. :)
