### ISSUE TITLE
have consistent use zig convention of `init` for constructors across codebase

### ISSUE THREAD

**Issue by jobez** [keep-starknet-strange/ziggy-starkdust#227]
## Description
The [Zig documentation for structs](https://ziglang.org/documentation/master/#toc-struct) uses `init` as the name for a constructor for a struct. There are several places where we are using `new.` 
 
### Objective
Make codebase consistent to zig conventions by a simple refactoring of usages of `new` to `init`

nonexhaustive list:

- Relocatable
- MemoryCell

**Comment by dhruvkelawala** [comment]
Can you please assign this to me?
