### ISSUE TITLE
feat: implement `opcodeAssertions` method in `CairoVM`

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#234]
## Description

To enhance the security measures within our `runInstruction` method in the `CairoVM` structure, we aim to implement a dedicated `opcodeAssertions` method. This method will handle the validation of specific instructions, ensuring the reliability and safety of our virtual machine implementation.

The proposed `opcodeAssertions` method will meticulously scrutinize various opcode types and their corresponding operands, verifying their adherence to predefined rules. By introducing this method, our goal is to effectively identify and respond to potential errors or inconsistencies within the instruction set, proactively mitigating runtime issues.

## References

- Reference to the Rust implementation: [Rust CairoVM Implementation](https://github.com/lambdaclass/cairo-vm/blob/8887e60f7ea5459188cb6624acc908ad29e75f60/vm/src/vm/vm_core.rs#L328-L360)
- Reference to the Python implementation: [Python Cairo VM Implementation](https://github.com/starkware-libs/cairo-lang/blob/ee7ce74e1159a349d4b77a5f952241b50b1692de/src/starkware/cairo/lang/vm/vm_core.py#L383-L408)

**Comment by dhruvkelawala** [comment]
Please assign this to me
