### ISSUE TITLE
feat: add `getFeltRange` method in `CairoVM`

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#235]
## Description

Following the successful merge of [Pull Request #222](https://github.com/keep-starknet-strange/ziggy-starkdust/pull/222), we need to implement its abstracted counterpart within the `CairoVM` structure. 

## Reference

- Reference for the Rust implementation: [Rust CairoVM Implementation](https://github.com/lambdaclass/cairo-vm/blob/8887e60f7ea5459188cb6624acc908ad29e75f60/vm/src/vm/vm_core.rs#L888-L894)

**Comment by ptisserand** [comment]
Can I work on this one?
