### ISSUE TITLE
refactor: encapsulate `setUpMemory` method in `Memory` structure

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#243]
## Current State

Currently, the `setUpMemory` function:
https://github.com/keep-starknet-strange/ziggy-starkdust/blob/00ee0d18d6bd2b2fdf05b54f0f27ae85cf231824/src/vm/memory/memory.zig#L798-L844

resides outside the `Memory` structure. This function operates directly on a `Memory` instance via a pointer passed as the first argument.

## Proposed Improvement
To streamline the structure and logical flow of our codebase, it's suggested to incorporate the `setUpMemory` function into the `Memory` structure itself. This integration would align more closely with the architecture, enhancing readability and encapsulation.

**Comment by lambda-0x** [comment]
i can take this up

**Comment by tcoratger** [comment]
> i can take this up

Assigned
