### ISSUE TITLE
feat: add programs that require no builtins

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#247]
## Description

In our pursuit of completing the Fibonacci suite within Rust Cairo, there are various programs in the Cairo repository that do not rely on any built-in functions. 

These programs, housed in [this directory](https://github.com/lambdaclass/cairo-vm/tree/main/cairo_programs), present an opportunity to enrich our repository by incorporating similar programs of this nature. These programs showcase diverse functionalities.

Expanding our repository's content by integrating programs akin to those found in the aforementioned directory could significantly enhance our project.

**Comment by lana-shanghai** [comment]
This is how to generate trace and memory from the [Rust VM](https://github.com/lambdaclass/cairo-vm/tree/main?tab=readme-ov-file#installing-project-dependencies): 

`target/release/cairo-vm-cli cairo_programs/factorial.json --trace_file cairo_programs/factorial.trace --memory_file cairo_programs/factorial.memory`
