### ISSUE TITLE
feat: implement `checkAutoDeductionsForAddress` in `CairoVM`

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#280]
## Description

In order to make sure that the value at the given address is consistent with the auto deduction rules, we need to implement a `checkAutoDeductionsForAddress` method in `CairoVM`.

## References
- Reference for the Rust implementation: https://github.com/lambdaclass/cairo-vm/blob/8a2ef24c1ca258f1d1d230cbbd1478cd1d4cf9db/vm/src/vm/vm_core.rs#L700-L721
- Reference for the Python implementation: https://github.com/starkware-libs/cairo-lang/blob/caba294d82eeeccc3d86a158adb8ba209bf2d8fc/src/starkware/cairo/lang/vm/virtual_machine_base.py#L477-L496

**Comment by dhruvkelawala** [comment]
Please assign this to me

**Comment by tcoratger** [comment]
> Please assign this to me

Assigned
