### ISSUE TITLE
feat: implement `checkAutoDeductions` for `CairoVM`

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#281]
## Description

In order to make sure that all assigned memory cells are consistent with their auto deduction rules, we need to implement a `checkAutoDeductions` method for `CairoVM` structure.

## References
- Reference to the Rust implementation: https://github.com/lambdaclass/cairo-vm/blob/8a2ef24c1ca258f1d1d230cbbd1478cd1d4cf9db/vm/src/vm/vm_core.rs#L674-L697
- Reference to the Python implementation: https://github.com/starkware-libs/cairo-lang/blob/caba294d82eeeccc3d86a158adb8ba209bf2d8fc/src/starkware/cairo/lang/vm/virtual_machine_base.py#L470-L475

**Comment by dhruvkelawala** [comment]
Please assign this to me

**Comment by tcoratger** [comment]
> Please assign this to me

Assigned
