### ISSUE TITLE
feat: implement `decodeCurrentInstruction` method for `CairoVM`

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#282]
## Description

In order to be able to decode our current instruction defined by the VM run context program counter, we need to implement a `decodeCurrentInstruction` method for `CairoVM`.

## References
- Reference for the Rust implementation: https://github.com/lambdaclass/cairo-vm/blob/8a2ef24c1ca258f1d1d230cbbd1478cd1d4cf9db/vm/src/vm/vm_core.rs#L434-L442

**Comment by dhruvkelawala** [comment]
Please assign this to me

**Comment by tcoratger** [comment]
> Please assign this to me

Assigned
