### ISSUE TITLE
feat: write memory to file 

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/ziggy-starkdust#308]
## Description

Following this [documentation](https://github.com/lambdaclass/cairo-vm_in_go/blob/main/README.md#writing-the-memory-into-a-file) assert that the memory to file output of the [Rust VM](https://github.com/lambdaclass/cairo-vm?tab=readme-ov-file#other-cli-arguments) is the same as the output of the Zig VM. 

## Acceptance criteria: 

The memory is the same for 4 Cairo programs: Fibonacci, factorial, output, and bitwise test. Comparison is done the same way as for the trace, see README.

**Comment by aniketpr01** [comment]
@lana-shanghai 
Task is to expand the function named writeEncodedMemory in cairo_run.zig, with reference to cairo_vm in Go.(Question: Can use Go or Rust version of cairo VM implementation right?)
I would like to give it a try!

**Comment by lana-shanghai** [comment]
Hey @aniketpr01 yes you can use both the Go and RUst VM for reference. The docs in the Go version are most helpful, but we usually compare with the output of the Rust VM as that's the most production ready version.
