### ISSUE TITLE
feat: add `isProofMode` utility function to `CairoRunner`

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#343]
### Issue Description

We require the addition of a utility function, `isProofMode`, within the `CairoRunner` struct. This utility function will serve to check whether the application is currently running in proof mode. 

### Action Items

**Implementation:**
   - Refer to the Rust implementation for guidance: https://github.com/lambdaclass/cairo-vm/blob/4ea224a1068b43aaa3899d24e834475106e8a78f/vm/src/vm/runners/cairo_runner.rs#L318-L321.
   - Ensure the implementation aligns with the existing logic in the Rust reference.

**Comment by StringNick** [comment]
assign me pls
