### ISSUE TITLE
feat: add generic `getNumberInputCells` method for builtins

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#348]
### Issue Description

We are in need of a generic method within the `BuiltinRunner` union (enum) that facilitates the invocation of the `n_input_cells` parameter of the builtins based on the specific builtin item. This generic method should utilize a switch mechanism to ensure the appropriate `n_input_cells` is returned for the corresponding builtin.

### Action Items

 **Generic Method Implementation:**
   - Develop a generic method inside the `BuiltinRunner` union to streamline the invocation of the `n_input_cells` parameter.
   - Implement a switch statement to dynamically call the relevant `n_input_cells` field based on the active builtin operation.

### Reference Implementation

- Refer to the Rust implementation for guidance: https://github.com/lambdaclass/cairo-vm/blob/4ea224a1068b43aaa3899d24e834475106e8a78f/vm/src/vm/runners/builtin_runner/mod.rs#L350-L362

**Comment by Godspower-Eze** [comment]
I can work on this

**Comment by tcoratger** [comment]
> I can work on this

Assigned
