### ISSUE TITLE
refactor: use AffinePoint instead of ECPoint

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/ziggy-starkdust#352]
##Description 

Currently the EC OP builtin [uses](https://github.com/keep-starknet-strange/ziggy-starkdust/blob/main/src/vm/builtins/builtin_runner/ec_op.zig#L25) the [ECPoint](https://github.com/keep-starknet-strange/ziggy-starkdust/blob/main/src/math/fields/elliptic_curve.zig#L22) struct, replace it with the [AffinePoint](https://github.com/keep-starknet-strange/ziggy-starkdust/blob/main/src/math/crypto/curve/ec_point.zig#L93). 

Make sure that the necessary operations such as `[ecDoubleSlope](https://github.com/keep-starknet-strange/ziggy-starkdust/blob/main/src/math/fields/elliptic_curve.zig#L106)` and [`ecOpImpl`](https://github.com/keep-starknet-strange/ziggy-starkdust/blob/main/src/math/fields/elliptic_curve.zig#L153) are implemented for the AffinePoint struct. 

Remove the unnecessary `elliptic_curve` file.

**Comment by oxlime** [comment]
can take this one

**Comment by lana-shanghai** [comment]
Hey @oxlime all good? Do you need any help? It was supposed to be an easy / quick one :)

**Comment by oxlime** [comment]
should been easy just havent had time to start, will finish by end of day  :)
