### ISSUE TITLE
feat: add step hint function 

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/ziggy-starkdust#363]
## Description 

Our VM is currently missing `stepHint` implementation, that [looks like so](https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/vm/vm_core.rs#L454) in the Rust VM. 

Step hint needs to be [called](https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/vm/vm_core.rs#L552) in step. 

Depends on `executeHint` implementation.

**Comment by StringNick** [comment]
assign me
