### ISSUE TITLE
feat: implement math hints

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/ziggy-starkdust#374]
Refer the [assert_nn](https://github.com/keep-starknet-strange/ziggy-starkdust/pull/373) hint, implement the other [math hints](https://github.com/lambdaclass/cairo-vm_in_go/blob/main/pkg/hints/math_hints.go#L36), see Go implementation for reference. 

Can be done in several PRs.

**Comment by StringNick** [comment]
assign me pls
