### ISSUE TITLE
feat: implement EC recover hints

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/ziggy-starkdust#393]
## Description 

Now that we have tested the full flow of an integration test with hints, we can actually run hints during `stepInstruction`. 

Look through the math hints and math utils files in order to understand the data flow. 

For reference, refer to the Rust implementation of the [hints](https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/hint_processor/builtin_hint_processor/ec_recover.rs) and [utils](https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/hint_processor/builtin_hint_processor/ec_utils.rs). 

Implement the accompanying tests. 

## Acceptance criteria

Add at least two programs that have the EC related hints, and ensure that the integration test passes. 
Programs can be taken from [here](https://github.com/lambdaclass/cairo-vm/tree/main/cairo_programs). Follow the README in the Cairo VM in Rust in order to compile the necessary files to json.

**Comment by StringNick** [comment]
assign me

**Comment by StringNick** [comment]
blocked by #432
