### ISSUE TITLE
Cairo runner: add unit tests for `initBuiltins` 

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#394]
We should add unit tests in order to confirm the validity of our `initBuiltins` implementation inside the Cairo runner:

Related:
- https://github.com/lambdaclass/cairo-vm/blob/4ea224a1068b43aaa3899d24e834475106e8a78f/vm/src/vm/runners/cairo_runner.rs#L1587-L1593
- https://github.com/lambdaclass/cairo-vm/blob/4ea224a1068b43aaa3899d24e834475106e8a78f/vm/src/vm/runners/cairo_runner.rs#L1616
- https://github.com/lambdaclass/cairo-vm/blob/4ea224a1068b43aaa3899d24e834475106e8a78f/vm/src/vm/runners/cairo_runner.rs#L1645
- https://github.com/lambdaclass/cairo-vm/blob/4ea224a1068b43aaa3899d24e834475106e8a78f/vm/src/vm/runners/cairo_runner.rs#L1677
- ...

**Comment by StringNick** [comment]
assign me

**Comment by tcoratger** [comment]
@StringNick assigned
