### ISSUE TITLE
Cairo runner: add unit tests for `initFunctionEntrypoint` function

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#395]
Now that #392 is merged, we should add unit tests to confirm validity of our `initFunctionEntrypoint` function inside the Cairo runner.

Related:
- https://github.com/lambdaclass/cairo-vm/blob/4ea224a1068b43aaa3899d24e834475106e8a78f/vm/src/vm/runners/cairo_runner.rs#L1769
- https://github.com/lambdaclass/cairo-vm/blob/4ea224a1068b43aaa3899d24e834475106e8a78f/vm/src/vm/runners/cairo_runner.rs#L1791
- https://github.com/lambdaclass/cairo-vm/blob/4ea224a1068b43aaa3899d24e834475106e8a78f/vm/src/vm/runners/cairo_runner.rs#L1818
- https://github.com/lambdaclass/cairo-vm/blob/4ea224a1068b43aaa3899d24e834475106e8a78f/vm/src/vm/runners/cairo_runner.rs#L4180

**Comment by Godspower-Eze** [comment]
I would like to work on this

**Comment by tcoratger** [comment]
@Godspower-Eze Assigned
