### ISSUE TITLE
Cairo runner: add unit tests for `initMainEntrypoint` function

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#396]
Now that #392 is merged, we can add unit test for our `initMainEntrypoint` function inside the Cairo runner.

Related: https://github.com/lambdaclass/cairo-vm/blob/4ea224a1068b43aaa3899d24e834475106e8a78f/vm/src/vm/runners/cairo_runner.rs#L1832-L851

**Comment by StringNick** [comment]
assign me
