### ISSUE TITLE
feat: implement bitwise builtin

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/ziggy-starkdust#4]
Builtins constrain certain memory cells in the area of memory shared between the CPU and the builtins.  

For inspiration, see the [Go](https://github.com/NethermindEth/cairo-vm-go/blob/main/pkg/vm/builtins/bitwise.go) and [Rust](https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/vm/runners/builtin_runner/bitwise.rs) implementations.

**Comment by jobez** [comment]
I can work on this 🧨

**Comment by abdelhamidbakhta** [comment]
> I can work on this 🧨

Let's go, assigned to you.

**Comment by jobez** [comment]
#41 added the deduction rule. once we have https://github.com/keep-starknet-strange/cairo-zig/issues/8 lined up, I can circle back and implement whatever conventions they decide to register the builtin with the VM and register/apply them to addresses

**Comment by tcoratger** [comment]
@jobez For your information, with the recent work, this can be implemented into this new file: https://github.com/keep-starknet-strange/cairo-zig/blob/main/src/vm/builtins/builtin_runner/bitwise.zig

**Comment by jobez** [comment]
> @jobez For your information, with the recent work, this can be implemented into this new file: https://github.com/keep-starknet-strange/cairo-zig/blob/main/src/vm/builtins/builtin_runner/bitwise.zig

Thank you!

**Comment by tcoratger** [comment]
@jobez Can be closed no?
