### ISSUE TITLE
Cairo runner: implement `checkRangeCheckUsage`

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#402]
In order to check that there are enough trace cells to fill the entire range check range, we need to implement a `checkRangeCheckUsage` function inside the Cairo runner.

## Reference for the function implementation
- https://github.com/lambdaclass/cairo-vm/blob/4ea224a1068b43aaa3899d24e834475106e8a78f/vm/src/vm/runners/cairo_runner.rs#L744-L769

## References for unit tests
- https://github.com/lambdaclass/cairo-vm/blob/4ea224a1068b43aaa3899d24e834475106e8a78f/vm/src/vm/runners/cairo_runner.rs#L4102
- https://github.com/lambdaclass/cairo-vm/blob/4ea224a1068b43aaa3899d24e834475106e8a78f/vm/src/vm/runners/cairo_runner.rs#L4125
- https://github.com/lambdaclass/cairo-vm/blob/4ea224a1068b43aaa3899d24e834475106e8a78f/vm/src/vm/runners/cairo_runner.rs#L4149

**Comment by StringNick** [comment]
assign me
