### ISSUE TITLE
Cairo runner: add unit test for trace relocation

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#404]
Now that #392 is merged, we need to add a unit test in the Cairo runner to confirm the proper trace relocation.

Reference:
- https://github.com/lambdaclass/cairo-vm/blob/4ea224a1068b43aaa3899d24e834475106e8a78f/vm/src/vm/runners/cairo_runner.rs#L2912-3054

**Comment by StringNick** [comment]
assign me
