### ISSUE TITLE
BuiltinHint: implement uint utils

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#416]
We need to implement uint utils for our builtin hint processor.

Rust reference: https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/hint_processor/builtin_hint_processor/uint_utils.rs

**Comment by TropicalDog17** [comment]
Hi, make I take this issue @tcoratger

**Comment by tcoratger** [comment]
> Hi, make I take this issue @tcoratger 

Assigned
