### ISSUE TITLE
BuiltinHint: implement squash dict utils

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#419]
We need to implement squash dict utils for our builtin hint processor.

Rust reference: https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/hint_processor/builtin_hint_processor/squash_dict_utils.rs

**Comment by StringNick** [comment]
assign me

**Comment by tcoratger** [comment]
> assign me

assigned
