### ISSUE TITLE
BuiltinHint: implement sha256 utils

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#420]
We need to implement sha256 utils for our builtin hint processor.

Rust reference: https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/hint_processor/builtin_hint_processor/sha256_utils.rs

**Comment by Godspower-Eze** [comment]
I would like to work on this

**Comment by tcoratger** [comment]
> I would like to work on this

@Godspower-Eze Assigned
