### ISSUE TITLE
BuiltinHint: implement dict hint utils

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#431]
We need to implement some dict hint utils in the context of our builtin hint processor.

Rust reference: https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/hint_processor/builtin_hint_processor/dict_hint_utils.rs

**Comment by StringNick** [comment]
assign me

**Comment by tcoratger** [comment]
> assign me

assigned
