### ISSUE TITLE
BuiltinHint: implement bigint

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#432]
We need to implement some bigint utils in the context of our builtin hint processor.

Rust reference: https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/hint_processor/builtin_hint_processor/bigint.rs

**Comment by swetshaw** [comment]
If this issue is unassigned, I would like to take this up

**Comment by tcoratger** [comment]
> If this issue is unassigned, I would like to take this up

@swetshaw Sure, just assigned.
