### ISSUE TITLE
Migrate `segment_used_sizes` to an `ArrayList`

### ISSUE THREAD

**Issue by tcoratger** [keep-starknet-strange/ziggy-starkdust#459]
### Issue Description
Currently, the `segment_used_sizes` data structure in the `segments` module is implemented as an `ArrayHashMap`, mapping segment indices to their respective sizes. However, this design includes redundant keys and does not fully optimize memory usage. As a result, it is proposed to redesign this data structure to enhance efficiency and simplicity.

### Proposed Solution
Replace the existing `ArrayHashMap` 

https://github.com/keep-starknet-strange/ziggy-starkdust/blob/efdac12e84b9a39420cc1863e19c928d9e4bb640/src/vm/memory/segments.zig#L35-L40

with an `ArrayList` to store the sizes used by each segment directly. By using an array where each index represents a segment, we can efficiently track and update the size used by each segment without the overhead of key-value pairs.

**Comment by tcoratger** [comment]
Require further investigations to know if this is something efficient when dealing with temporary segments which could lead to negative indexes.

**Comment by StringNick** [comment]
issue done in #514 pull request
