### ISSUE TITLE
feat: implement pedersen hash builtin

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/ziggy-starkdust#6]
### Description
A cell is constrained by values in two other cells if these memory cells are initialized with the Pedersen hash builtin. 
Linked to the [issue](https://github.com/keep-starknet-strange/cairo-zig/issues/22) to implement the primitive first 

### Acceptance Criteria
Implementation and passing tests. 

### Resources
See [test](https://github.com/NethermindEth/cairo-vm-go/blob/main/pkg/vm/builtins/pedersen_test.go) to understand the logic. 

See [Rust](https://github.com/lambdaclass/cairo-vm/blob/main/vm/src/vm/runners/builtin_runner/hash.rs) and [Go](https://github.com/NethermindEth/cairo-vm-go/blob/main/pkg/vm/builtins/pedersen.go) implementations

**Comment by tcoratger** [comment]
With the recent work that have been done, this implementation can be done directly into this file: https://github.com/keep-starknet-strange/cairo-zig/blob/main/src/vm/builtins/builtin_runner/hash.zig

**Comment by edisontim** [comment]
Hey! Can I take this :) ?

**Comment by tcoratger** [comment]
> Hey! Can I take this :) ?

@edisontim Assigned
