### ISSUE TITLE
feat: implement signature builtin 

### ISSUE THREAD

**Issue by lana-shanghai** [keep-starknet-strange/ziggy-starkdust#81]
### Description 

Builtins constrain certain memory cells in the area of memory shared between the CPU and the builtins.
For inspiration see [Rust](https://github.com/lambdaclass/cairo-vm/blob/01a5773d4198d083ea645dea5c00133c36ff8321/vm/src/vm/runners/builtin_runner/signature.rs).

**Comment by oxlime** [comment]
Would like to work on this one

**Comment by tcoratger** [comment]
> Would like to work on this one

@oxlime Assigned

**Comment by edisontim** [comment]
Hey, if this is stale can I grab this?

**Comment by lana-shanghai** [comment]
How's it going @edisontim ? :)

**Comment by StringNick** [comment]
assign me
